### ISSUE TITLE
Task 2 -  Select some Amenities to be comfortable!

### ISSUE THREAD

**Issue by yeungegs** [yeungegs/AirBnB_clone_v4#3]
- [x] Replace the route 0-hbnb with 1-hbnb in the file 1-hbnb.py (based on 0-hbnb.py)
Create a new template 1-hbnb.html (based on 0-hbnb.html) and update it:
- [x] Import jQuery in the <HEAD> tag
- [x] Import the javascript static/scripts/1-hbnb.js in the <HEAD> tag
- [x] Add a <INPUT type="checkbox"> tag to the LI tag of each amenity
- [x] The new checkbox must be at 10px on the left of the Amenity name
- [x] Add to the INPUT tags of each amenity ( LI tag) the attribute data-id=":amenity_id" => this will allow us to retrieve the Amenity ID from the DOM
- [x] Add to the INPUT tags of each amenity ( LI tag) the attribute data-name=":amenity_name" => this will allow us to retrieve the Amenity name from the DOM

Write a Javascript script (static/scripts/1-hbnb.js):
- [x] Your script must be executed only when DOM is loaded
- [x] You must use jQuery
Listen for changes on each INPUT checkbox tag:
- [x] If the checkbox is checked, you must store the Amenity ID in a variable (dictionary or list)
- [x] if the checkbox is unchecked, you must remove the Amenity ID from the variable
- [x] update the H4 tag inside the DIV Amenities with the list of Amenities checked

**Comment by spencerhcheng** [comment]
- [ ] Replace the route 0-hbnb with 1-hbnb in the file 1-hbnb.py (based on 0-hbnb.py)
Create a new template 1-hbnb.html (based on 0-hbnb.html) and update it:
- [ ] Import jQuery in the <HEAD> tag
- [ ] Import the javascript static/scripts/1-hbnb.js in the <HEAD> tag
- [ ] Add a <INPUT type="checkbox"> tag to the LI tag of each amenity
- [ ] The new checkbox must be at 10px on the left of the Amenity name
- [ ] Add to the INPUT tags of each amenity ( LI tag) the attribute data-id=":amenity_id" => this will allow us to retrieve the Amenity ID from the DOM
- [ ] Add to the INPUT tags of each amenity ( LI tag) the attribute data-name=":amenity_name" => this will allow us to retrieve the Amenity name from the DOM

Write a Javascript script (static/scripts/1-hbnb.js):
- [ ] Your script must be executed only when DOM is loaded
- [ ] You must use jQuery
Listen for changes on each INPUT checkbox tag:
- [ ] If the checkbox is checked, you must store the Amenity ID in a variable (dictionary or list)
- [ ] if the checkbox is unchecked, you must remove the Amenity ID from the variable
- [ ]update the H4 tag inside the DIV Amenities with the list of Amenities checked

**Comment by yeungegs** [comment]
moving comment from @spencerhcheng to issue description

**Comment by yeungegs** [comment]
We need to fix the hardcoding of '30' for the amenities header.
